[loggers]
keys=root,async_re,sync_re,rbfe_structprep,abfe_structprep,atom_openmm,atom_openmm_neqti,atom_openmm_equilibration

[handlers]
keys=stdout,stderr

[formatters]
keys=async_re

[logger_root]
handlers=

[logger_async_re]
level=INFO
handlers=stdout,stderr
qualname=async_re
propagate=0

[logger_rbfe_structprep]
level=INFO
handlers=stdout,stderr
qualname=rbfe_structprep
propagate=0

[logger_abfe_structprep]
level=INFO
handlers=stdout,stderr
qualname=abfe_structprep
propagate=0

[logger_sync_re]
level=INFO
handlers=stdout,stderr
qualname=sync_re
propagate=0

[logger_atom_openmm]
level=INFO
handlers=stdout,stderr
qualname=atom_openmm
propagate=0

[logger_atom_openmm_neqti]
level=INFO
handlers=stdout,stderr
qualname=atom_openmm.neqti
propagate=0

[logger_atom_openmm_equilibration]
level=INFO
handlers=stdout,stderr
qualname=atom_openmm.equilibration
propagate=0

[handler_stdout]
class=atom_openmm.utils.logging_filters.MaxLevelStreamHandler
formatter=async_re
level=DEBUG
args=(sys.stdout, 'INFO')

[handler_stderr]
class=StreamHandler
formatter=async_re
level=WARNING
args=(sys.stderr,)

[formatter_async_re]
format=%(asctime)s - %(levelname)-8s - %(name)-30s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
